### ISSUE TITLE
Playing song issue

### ISSUE THREAD

**Issue by VeronicaM** [mahaveer0496/sound-cloud-react#1]
If you play  a song then put it on pause and switch to a new tab in the menu the song starts playing again, but if the song was playing when you switched the tab, it stops playing..

**Comment by mahaveer0496** [comment]
We're sorry for the inconvenience, will get back to you ASAP with a fix or a cause 😄

**Comment by mahaveer0496** [comment]
@VeronicaM the issue is because of this.
Since `Player` and `List_item` are connected to each other by `trackPlayHandler()` and the state `playTrack`, once the new track is searched for ( or `Lower_nav` is clicked ), that particular list item is gone and so it messes up that `playTrack` state.
No idea on how to fix that.
Our team is looking forward to your collaboration and help in fix them bugs in this awesome open source project 😄

**Comment by VeronicaM** [comment]
fixed :)
